# Generated by Django 5.0.2 on 2025-08-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField(unique=True)),
                ('title', models.TextField()),
                ('category', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('square_meters', models.FloatField()),
                ('region', models.TextField()),
                ('town', models.TextField(blank=True, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('address_city', models.CharField(blank=True, max_length=255, null=True)),
                ('address_state', models.CharField(blank=True, max_length=255, null=True)),
                ('address_country', models.CharField(blank=True, max_length=255, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('land_area', models.FloatField(blank=True, null=True)),
                ('built_up', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photos', models.JSONField(default=list)),
                ('main_image', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('platform', models.TextField()),
                ('link', models.TextField()),
                ('energy_rating', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=1, null=True)),
                ('company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('property_created_at', models.DateTimeField(blank=True, null=True)),
                ('on_off', models.BooleanField(blank=True, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
